# .streamlit/secrets.toml
[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1b3rZT7-WdKVi-AKM6I4a53ylPrmLlErSZ-UtR1i8Jzw"
type = "service_account"
project_id = "prioritisation-matrix"
private_key_id = "9c82a99db68708682f5c403f046cea25e206db73"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDB+zo2Mok7c3mX
cSpQUcoUBSd6FvNRmjmpaTymUmNewG0j03DmBnU3bIsQmiCLHU3ONwkQ/dmxqfkY
lfM1SvURdtp3lPKwfcReBNLcGq2W3Z6pW5MTbvKzKOT84Hh8ighVUr4dSk4yblhg
bVXaI40Y7GlRWS1OGwnoOf8cwlWwuRybfobpY3sj8uq+nvi3bHQJfb34emQb2x2p
y+rzcw1KObgINXZEWhUdURwJ4WLX4rWJeHderSIJtrGVruQMX0HGe0v8iuEI4CY+
EwC6J3T7i2vbuGVmN4ES/cpGe5P60tzar8FIy9LsBOOJICGQ+YmpfyBXyW7NGtT4
3YFHi/A9AgMBAAECgf8prM/U1QamvyhgYO+2UdwYcQMKN+QOpBO/Udy13v16Xd0U
1VhsEvcb8TXvWy2itakBpNFN1Tvv75SUs6KM0I3WMrK8/kMlp9+IU4D5yMGCqBpu
SD5Q7oU1+JM5wQAhwYYIzr4JjO0/6HUUQmkvdHPb5u65i28wWJ7IRa2JgDbowHwH
ziu2PY3dNSoewMqiPJLE/j0BYIZipPmA+HuHVm5mo8LVUkPn2CRrezs2dGI8+bDh
T8isPLn//J0SzWUicYpeqk5YrlmjNnucVnvuMqKYyqvPs4ubaWNl8bSEhHPsZMiN
MOXl+kccuJhE9DWN1gAHF4NlkfqaH3xbiyqgx+UCgYEA+XjwFSom8OYwI/hHRsg/
L7OqJCgo/F88n/EIo4BfzqLZXQCTC/QHff6TTxm4EIWJnVhvGXq3x32MXoIlKm5b
eRNZQyyKw0rOnSvy0TdBxhuHalOUacnoJpiwEih5Z/5uC5g77Ys/mDYuGBC599/O
TG0qrjp+t4oMCqUcTi/pbQ8CgYEAxw6W0RXCSJdOR5OGptMeVuzKQWJmNaSO2h9q
6Ajbk6cL0di0kyXr96LSCt8BTxjScUzzqG9/IZbPCFLEDbFiYysxgcbAXWxSI34D
0SvxA5zdhbTzxvmZ2QkMEw8CTyunWH8UpMdve3SuRIh2jbpElk6FILaA0mMqTxJ0
SZDl5fMCgYEA30h4EWld2yUbl0YjfV3C+A3lTWFIdcFDwJ96LOS8W3Tz+UKHWh57
CjDtZdHOJbNvnQ3GulZU4M8k8H2piBWn93Dy5qWaOPrefFwWg1zimM6Q4ACYiCq3
hrwIcugY6ZQWqHgDwzNrou9zSATIfeupeEwI9FHUkq+S4YAwGmbVlM8CgYByI7hx
HcPwsent+vbL8+TCvTZgdZbcDYboJfm8IVAfAzsw0c0BT05WCePc3fC3NSl+VDyn
CX/hd8MxJ5xJqbwb1ymlG500NKeIuHph14t0od8YCyF5p6gDHj/xMbsGQKbNhNkG
f2E6bjZ7D7DDJdqsQUvu7RdDDB+3hYJuqIpa5wKBgQCFyJ0QX50Z+1Wk/niZ+wrh
S4bgcp0650FR9e0COOt8ytS9pHXpyYnZ6rqu3stFY0Y9YvH0XxHv3XFHdYUXJHfn
Dx2JvqoJV6P5FZkZ5X0x5YFdxb/GENoJFKVTjQwAUNQQz2dqwZEQWbOrcfQnKrpD
OS3Xo6hrtF7FdhT/YtwVKg==
-----END PRIVATE KEY-----"""
client_email = "streamlit-gsheets@prioritisation-matrix.iam.gserviceaccount.com"
client_id = "116916326934671868446"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-gsheets%40prioritisation-matrix.iam.gserviceaccount.com"